### PR TITLE
Add capture for option and option_value

### PR DESCRIPTION
**Pull request by afh**
Ledger journal files may include any of the command-line options, e.g. `--sort date`.

### CODE REVIEW

**Comment by cbarrete** [comment]
Hi, thanks for all the PRs! I have not missed them, I'll get to them ASAP, hopefully within a week.

**Comment by afh** [comment]
Thanks for the heads up, @cbarrete, very much appreciated. Open source work is something that people usually have to squeeze into their busy day, hence patience is a useful virtue to have 🙂

**Comment by cbarrete** [comment]
LGTM, can you rebase this branch?

**Comment by afh** [comment]
✅ Done! I went ahead and improved option parsing to allow for option values to be separated by an equals than a blank-space, e.g.: `--date-format=%Y-%m-%d`.

**Pull request merged**
