### PR TITLE
 Correctly parse non-US currency formats

### PR DESCRIPTION
**Pull request by gregorias**
Ledger can parse international currency formats that can contain commas,
spaces, and apostrophes, so tree-sitter-ledger should too.

### CODE REVIEW

**Comment by cbarrete** [comment]
What program/version are you using? With the latest release of the standard `ledger` I get
```
  Assets:Bank  1'000.00 CHF
               ^^^^^^^^^^^^
Error: Unexpected char '0' (Note: inline math requires parentheses)
```

**Comment by gregorias** [comment]
```
  Assets:Bank  1'000.00 CHF
```

doesn't work. I mistakenly thought that ledger does support it.

**Comment by cbarrete** [comment]
Same for  `Assets:Bank  1 000,00 PLN`

**Comment by gregorias** [comment]
```
Assets:Bank  1 000,00 PLN
```

works in hledger. In hledger, you can specify the format with the `commodity` directive, e.g.,

```
commodity PLN
  format  1 234,00 PLN
```

My case is that this is worthwhile to support in the parser, and there's no cost to it.

**Comment by cbarrete** [comment]
Sure, I was a bit wary about adding support for hledger since I'd like to keep the opportunity of moving this repo to https://github.com/ledger/ at some point if they're interested, but https://github.com/ledger/vim-ledger has some support for hledger, so that's fine.

Thanks for your contribution!

**Pull request merged**
